<a href="https://colab.research.google.com/github/Ritiksingh2912/Ritiksingh2912/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
                      #  Assignment NumPy

                     # Question and answer

In [ ]:
import numpy as np
# Q1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
#Answer =
l = [0,1,2,3,4,5]
arr = np.array(l)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#Q2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
#answer=
if arr.dtype == np.float64:
    print("The data type of arr is float64.")
else:
    print("The data type of arr is not float64.")

The data type of arr is float64.


In [ ]:
#Q3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
#answer=
arr = np.array([1+2j, 3-4j, 5+6j], dtype=np.complex128)
print("Array 'arr':", arr)

Array 'arr': [1.+2.j 3.-4.j 5.+6.j]


In [ ]:
#Q4. Convert an existing NumPy array 'arr' of integers to float32 data type.
# answer=
arr = np.array([1, 2, 3, 4, 5])
# Convert 'arr' to float32 data type
arr_float32 = arr.astype(np.float32)
print("Original array 'arr':", arr)
print("Converted array to float32 data type:", arr_float32)

Original array 'arr': [1 2 3 4 5]
Converted array to float32 data type: [1. 2. 3. 4. 5.]


In [ ]:
#Q5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
#answer=
# Example array 'arr' with float64 data type
arr = np.array([1.5, 2.6, 3.7], dtype=np.float64)
# Convert 'arr' to float32 data type
arr_float32 = arr.astype(np.float32)
print("Original array 'arr':", arr)
print("Converted array to float32 data type:", arr_float32)

Original array 'arr': [1.5 2.6 3.7]
Converted array to float32 data type: [1.5 2.6 3.7]


In [ ]:
#Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
#answer=
arr = np.fromfunction(lambda i, j: i==j, (3,3))
arr

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
# data types
type(arr)

numpy.ndarray

In [ ]:
# shape
arr.shape

(3, 3)

In [ ]:
#size
arr.size

9

In [ ]:
#Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
#answer=
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# DIMENSION
arr.ndim

2

In [ ]:
#Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes
#answer-
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.size * item_size
    return item_size, total_size
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)
print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)

Item size (bytes): 8
Total size (bytes): 48


In [ ]:
#Q9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
#answe-
def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print("Strides:", strides)

Strides: (24, 8)


In [ ]:
#Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
#answer-
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (24, 8)


In [ ]:
#Q11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements
#answer-
def create_zeros_array(n):
    return np.zeros(n)
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [ ]:
arr1 = np.zeros((1,3,4))
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#Q12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D  NumPy array filled with ones of size `rows x cols`.
#Answer -
import numpy as np
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Q13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
#Ans-
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)

[0 2 4 6 8]


In [ ]:
#Q14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive)
#Ans-
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#Q15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`
#ans-
def create_identity_matrix(n):
    return np.eye(n)
n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Q16. Write a function that takes a Python list and converts it into a NumPy array.
#Ans-
import numpy as np
def list_to_numpy_array(input_list):
    return np.array(input_list)
my_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(my_list)
print(numpy_array)

[1 2 3 4 5]


In [ ]:
#Q17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
#ans-
original_array = np.array([1, 2, 3, 4, 5])
array_view = original_array.view()
array_view[0] = 100
# Print both arrays
print("Original array:", original_array)
print("Array view:", array_view)

Original array: [100   2   3   4   5]
Array view: [100   2   3   4   5]


In [ ]:
#Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis
#ans-
def concatenate_arrays(arr1, arr2, axis=0):
    """ Concatenates two NumPy arrays along a specified axis.
    Parameters:
    arr1 : numpy.ndarray
        The first array to concatenate.
    arr2 : numpy.ndarray
        The second array to concatenate.
    axis : int, optional
        The axis along which to concatenate the arrays. Default is 0.
    Returns:
    numpy.ndarray
        The concatenated array.
    """
    return np.concatenate((arr1, arr2), axis=axis)
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

concatenated_array = concatenate_arrays(array1, array2, axis=1)
print("Concatenated array along axis 1:")
print(concatenated_array)

Concatenated array along axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#Q19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
#ans-
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8],
                   [9, 10]])
result = np.concatenate((array1, array2), axis=1)
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated array:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Concatenated array:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [ ]:
#Q20. Write a function that vertically stacks multiple NumPy arrays given as a list.
#ans-
import numpy as np
def stack_arrays_vertically(arrays):
    """
    Stack multiple NumPy arrays vertically.

    Parameters:
        arrays (list of numpy.ndarray): List of NumPy arrays to be stacked.

    Returns:
        numpy.ndarray: Vertically stacked array.
    """
    return np.vstack(arrays)
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

stacked_array = stack_arrays_vertically([array1, array2])
print(stacked_array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
#ans-
import numpy as np
def create_integer_array(start, stop, step):
   """
   Create an array of integers within a specified range (inclusive) with a given step size.
    Parameters:
        start (int): The starting value of the range.
        stop (int): The ending value of the range.
        step (int): The step size between values in the range.
    Returns:
        numpy.ndarray: The array of integers within the specified range.
    """
    return np.arange(start, stop+1, step, dtype=int)
start = 0
stop = 10
step = 2
result = create_integer_array(start, stop, step)
print(result)

[ 0  2  4  6  8 10]


In [ ]:
#Q22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
#ans
def generate_equally_spaced_array(start, stop, num_values):
    """   Generate an array of equally spaced values between two endpoints.
    Parameters:
        start (float): The starting value of the range.
        stop (float): The ending value of the range.
        num_values (int): The number of values to generate.
    Returns:
        numpy.ndarray: The array of equally spaced values between the specified endpoints.
    """   return np.linspace(start, stop, num_values)
start = 0
stop = 1
num_values = 10
result = generate_equally_spaced_array(start, stop, num_values)
print(result)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
#Ans-
def generate_logarithmically_spaced_array(start, stop, num_values):
    """
    Generate an array of logarithmically spaced values between two endpoints.
    Parameters:
        start (float): The starting value of the range.
        stop (float): The ending value of the range.
        num_values (int): The number of values to generate.
    Returns:
        numpy.ndarray: The array of logarithmically spaced values between the specified endpoints.
    """
    return np.logspace(np.log10(start), np.log10(stop), num_values)
start = 1
stop = 1000
num_values = 5
result = generate_logarithmically_spaced_array(start, stop, num_values)
print(result)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
#Q24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
#Ans-
import pandas as pd
# Create a NumPy array with random integers
random_array = np.random.randint(1, 101, size=(5, 3))
# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])
print(df)

   Column1  Column2  Column3
0       47       85       74
1       68        6       45
2       89       46        1
3       83       80       59
4       45       21       98


In [ ]:
#Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
#ans-
def replace_negative_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {'A': [-1, 2, -3, 4],
        'B': [5, -6, 7, -8]}
df = pd.DataFrame(data)
# Call the function to replace negative values in column 'A'
df = replace_negative_with_zero(df, 'A')
print(df)

   A  B
0  0  5
1  2 -6
2  0  7
3  4 -8


In [ ]:
#Q26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
#ans-
arr[2]

30

In [ ]:
#Q27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#ans-
arr_2d[1,2]

6

In [ ]:
#Q28. . Using boolean indexing, extract elements greater than 5 from the given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])
#Ans-
greater_than_5 = arr[arr > 5]
print(greater_than_5)

[ 8 10  7]


In [ ]:
#Q29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
#Ans-
arr[1:5]

array([2, 3, 4, 5])

In [ ]:
#Q30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#Ans-
arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
#Q31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
#Ans-
def extract_elements(arr, indices):
    # Ensure indices are within bounds
    indices = np.clip(indices, 0, arr.size - 1)
    # Flatten the array and extract elements based on indices
    return arr.flatten()[indices]
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
indices = np.array([0, 4, 8])  # Indices to extract elements from arr
result = extract_elements(arr, indices)
print(result)

[1 5 9]


In [ ]:
#Q32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
#ans-
arr = np.array([3, 8, 2, 9, 6, 10, 5, 7])
#Ans-
greater_than_5 = arr[arr > 5]
print(greater_than_5)

[ 8  9  6 10  7]


In [ ]:
#Q33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
#Ans-
def extract_elements_3d(arr, indices_dim1, indices_dim2, indices_dim3):
    # Ensure indices are within bounds
    indices_dim1 = np.clip(indices_dim1, 0, arr.shape[0] - 1)
    indices_dim2 = np.clip(indices_dim2, 0, arr.shape[1] - 1)
    indices_dim3 = np.clip(indices_dim3, 0, arr.shape[2] - 1)
    # Use advanced indexing to extract elements
    return arr[indices_dim1, indices_dim2, indices_dim3]
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

indices_dim1 = np.array([0, 1, 2])  # Indices for the first dimension
indices_dim2 = np.array([0, 1, 2])  # Indices for the second dimension
indices_dim3 = np.array([0, 1, 2])  # Indices for the third dimension
result = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print(result)  # Output: [ 1 14 27]

[ 1 14 27]


In [ ]:
#Q34.Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing
#ans-
def elements_satisfying_conditions(arr, condition1, condition2):
    # Boolean indexing to filter elements satisfying both conditions
    filtered_arr = arr[(condition1) & (condition2)]
    return filtered_arr
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = arr > 3
condition2 = arr % 2 == 0
result = elements_satisfying_conditions(arr, condition1, condition2)
print(result)

[4 6 8]


In [ ]:
#Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
#ans=
def extract_elements_2d(arr, row_indices, col_indices):
    # Ensure indices are within bounds
    row_indices = np.clip(row_indices, 0, arr.shape[0] - 1)
    col_indices = np.clip(col_indices, 0, arr.shape[1] - 1)
    return arr[row_indices, col_indices]
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

row_indices = np.array([0, 1, 2])  # Row indices
col_indices = np.array([0, 1, 2])  # Column indices
result = extract_elements_2d(arr_2d, row_indices, col_indices)
print(result)  # Output: [1 5 9]

[1 5 9]


In [ ]:
#Q36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
#ans-
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
# Add scalar value of 5 to each element using broadcasting
arr += 5
print(arr)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
#Q37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
#Ans-
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
# Reshape arr1 to match the shape of arr2 for broadcasting
arr1_reshaped = arr1.reshape((3, 1))
# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr1_reshaped * arr2
print(result)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [ ]:
#Q38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
#Ans-
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])
# Reshape arr1 to match the shape of arr2 along the rows
arr1_reshaped = arr1.reshape(4, 1)
# Perform broadcasting and addition
result = arr2 + arr1_reshaped
print(result)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [ ]:
#Q39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
#Ans-
# Define the arrays
arr1 = np.array([[1],
                  [2],
                  [3]])
arr2 = np.array([[4, 5, 6]])
# Perform broadcasting and addition
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#Q40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility
#ams
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
arr2 = np.array([[2, 2], [2, 2]])        # Shape: (2, 2)
# Expand dimensions of arr2 to match the shape of arr1
expanded_arr2 = np.expand_dims(arr2, axis=-1)  # Shape: (2, 2, 1)
# Perform multiplication
result = arr1 * expanded_arr2
print(result)

[[[ 2  4  6]
  [ 8 10 12]]

 [[ 2  4  6]
  [ 8 10 12]]]


In [ ]:
#Q41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
#ans-
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Calculate column-wise mean
column_means = np.mean(arr, axis=0)
print("Column-wise mean:", column_means)

Column-wise mean: [2.5 3.5 4.5]


In [ ]:
#Q42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
#ans-
np.max(arr, axis=1)

array([3, 6])

In [ ]:
#Q43.For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
#Ans-
np.argmax(arr, axis=0)

array([1, 1, 1])

In [ ]:
#Q44.  For the given array, apply custom function to calculate moving sum along rows
arr = np.array([[1, 2, 3], [4, 5, 6]])
#ans-
def moving_sum_along_rows(arr, window_size):
    # Initialize an empty array to store the moving sums
    moving_sums = np.zeros_like(arr, dtype=float)

    # Iterate through each row
    for i in range(arr.shape[0]):
        # Calculate the moving sum for the current row
        for j in range(arr.shape[1] - window_size + 1):
            moving_sums[i, j:j+window_size] = np.sum(arr[i, j:j+window_size])

    return moving_sums
arr = np.array([[1, 2, 3], [4, 5, 6]])
window_size = 2
result = moving_sum_along_rows(arr, window_size)
print("Moving sum along rows:")
print(result)

Moving sum along rows:
[[ 3.  5.  5.]
 [ 9. 11. 11.]]


In [ ]:
#Q45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
#ans-
arr = np.array([[2, 4, 6], [3, 5, 7]])
# Check if all elements in each column are even
are_columns_even = np.all(arr % 2 == 0, axis=0)
print("Are all elements in each column even?", are_columns_even)

Are all elements in each column even? [False False False]


In [ ]:
#Q46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
#ans-
def reshape_matrix(arr, m, n):
    reshaped_matrix = np.reshape(arr, (m, n))
    return reshaped_matrix
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
reshaped_matrix = reshape_matrix(original_array, m, n)
print("Reshaped matrix:")
print(reshaped_matrix)

Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [ ]:
#Q47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
#Ans-
def flatten_matrix(matrix):
    flattened_array = matrix.flatten()
    return flattened_array
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print("Flattened array:")
print(flattened_array)

Flattened array:
[1 2 3 4 5 6]


In [ ]:
#Q48.  Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
#ans
def concatenate_arrays(array1, array2, axis=0):
    """
    Concatenates two arrays along the specified axis.
    Parameters:
        array1 (numpy.ndarray): First array.
        array2 (numpy.ndarray): Second array.
        axis (int, optional): Axis along which arrays will be concatenated. Default is 0.
    Returns:
        numpy.ndarray: Concatenated array.
    """
    return np.concatenate((array1, array2), axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result)
result = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:\n", result)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Q49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#ans-
def split_array(original_array, num_splits, axis=0):
    """
    Splits an array into multiple sub-arrays along the specified axis.
    Parameters:
        original_array (numpy.ndarray): Original array.
        num_splits (int): Number of splits along the specified axis.
        axis (int, optional): Axis along which to split the array. Default is 0.
    Returns:
        list of numpy.ndarray: List of sub-arrays.
    """
    return np.split(original_array, num_splits, axis=axis)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = split_array(original_array, num_splits=3, axis=0)
print("Split along axis 0:\n", result)
result = split_array(original_array, num_splits=3, axis=1)
print("\nSplit along axis 1:\n", result)

Split along axis 0:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

Split along axis 1:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [ ]:
#Q50. Write a function that inserts and then deletes elements from a given array at specified indices
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
#Ans-
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    """
    Inserts elements into and then deletes elements from a given array at specified indices.
    Parameters:
        original_array (numpy.ndarray): Original array.
        indices_to_insert (list): Indices at which to insert elements.
        values_to_insert (list): Values to insert at specified indices.
        indices_to_delete (list): Indices at which to delete elements.
    Returns:
        numpy.ndarray: Updated array.
    """
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)

    original_array = np.delete(original_array, indices_to_delete)
    return original_array
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Updated array:", result)

Updated array: [ 1 10 11  4  5]


In [ ]:
#Q51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
#Ans-
# Create a NumPy array arr1 with random integers
arr1 = np.random.randint(1, 100, size=10)
# Create another NumPy array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)
# Perform element-wise addition between arr1 and arr2
result = arr1 + arr2
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nElement-wise addition result:")
print(result)

arr1:
[ 1 28 86 18 88  7 78 54 47 79]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Element-wise addition result:
[ 2 30 89 22 93 13 85 62 56 89]


In [ ]:
#Q52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
#Ans
arr1 = np.arange(10, 0, -1)  # Creates an array with integers from 10 to 1 in descending order
print("arr1:")
print(arr1
arr2 = np.arange(1, 11)  # Creates an array with integers from 1 to 10
print("\narr2:")
print(arr2)
result = arr1 - arr2
print("\nResult of element-wise subtraction:")
print(result)

arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
#Q53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
#Ans-
# Create a NumPy array arr1 with random integers
arr1 = np.random.randint(1, 100, size=5)
# Create another NumPy array arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
# Perform element-wise multiplication between arr1 and arr2
result = arr1 * arr2
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nElement-wise multiplication result:")
print(result)

arr1:
[84 93 81 51 10]

arr2:
[1 2 3 4 5]

Element-wise multiplication result:
[ 84 186 243 204  50]


In [ ]:
#Q54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
#Ans-
arr1 = np.arange(2, 11, 2)  # Creates an array with even integers from 2 to 10
print("arr1:")
print(arr1)
arr2 = np.arange(1, 6)  # Creates an array with integers from 1 to 5
print("\narr2:")
print(arr2)
result = arr1 / arr2
print("\nResult of element-wise division:")
print(result)

arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [ ]:
#Q55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise
#Ans
arr1 = np.array([1, 2, 3, 4, 5])# Create arr1 with integers from 1 to 5
print("arr1:")
print(arr1)
arr2 = arr1[::-1]# Create arr2 with the same numbers reversed
print("\narr2:")
print(arr2)
result = np.power(arr1, arr2)
print("\nResult of element-wise exponentiation:")
print(result)

arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


In [ ]:
#Q56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
#Ans-
def count_substring_occurrences(arr, substring):
    """
    Count the occurrences of a specific substring within a NumPy array of strings.

    Parameters:
        arr (numpy.ndarray): The NumPy array of strings.
        substring (str): The substring to count occurrences of.

    Returns:
        int: The number of occurrences of the substring.
    """
    # Join all strings in the array into a single string
    joined_string = ' '.join(arr)
    # Count occurrences of the substring in the joined string
    count = joined_string.count(substring)
    return count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print(f"The substring '{substring}' occurs {occurrences} times in the array.")

The substring 'hello' occurs 3 times in the array.


In [ ]:
#Q57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
#Ans-
np.char.upper(arr)

array(['HELLO', 'WORLD', 'OPENAI', 'GPT'], dtype='<U6')

In [ ]:
#Q58.  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
#ans-
arr[0] = ('mango')
arr

array(['mango', 'banana', 'grape', 'pineapple'], dtype='<U9')

In [ ]:
#Q59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
#Ans-
def concatenate_strings(arr1, arr2):
    """
    Concatenate strings in two NumPy arrays element-wise.
    Parameters:
        arr1 (numpy.ndarray): The first NumPy array of strings.
        arr2 (numpy.ndarray): The second NumPy array of strings.
    Returns:
        numpy.ndarray: A NumPy array with concatenated strings.
    """
       concatenated_arr = np.char.add(arr1, arr2) # Use np.char.add to concatenate strings element-wise
    return concatenated_arr
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_arr = concatenate_strings(arr1, arr2)
print("Array with concatenated strings:")
print(concatenated_arr)

Array with concatenated strings:
['HelloOpen' 'WorldAI']


In [ ]:
#Q60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
#ANS-
def longest_string_length(arr):
    # Use max() function with a lambda function to find the length of each string
    max_length = max(len(s) for s in arr)
    return max_length
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))

9


In [ ]:
#Q 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and  standard deviation of the dataset using NumPy's functions.
#ans-
dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)# Compute the mean of the dataset
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)# Compute the standard deviation of the dataset
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Dataset: [939 193 607 400 260   8 794 199 526 916 741 694 696 582  51 693 380 188
   9 655 191 730 780 425 945 623 816 492 633 430 969 185  79 397   5 909
 116  10 613  68 799  78 416 150 440 626 622 378 793 236 628 414 140 829
 106 633 980 789 718 673 275 210  32 344  69 216 201 544 506 816 985 689
 944 277 277 494 647  72  76 717  16 297  24  89 894  64 864 910 582  47
 765 751  65 360 656 887 378 404 361 520]
Mean: 467.2
Median: 466.0
Variance: 90337.0
Standard Deviation: 300.56114186634306


In [ ]:
#Q62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
#ans-
random_numbers = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)
print("Random Numbers:", random_numbers)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Random Numbers: [ 9 69 16 63 93 58 53 38 30 79 57 38 22 37 79 22 17 78 16 81 57 28 69 84
 14  5 10 25 47  9 50 79  8 72 92 26 29 42 12 93 60 45 87 48 23 27  5 33
 48 20]
25th Percentile: 22.0
75th Percentile: 67.5


In [ ]:
#Q63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
#Ans-
array1 = np.random.rand(100)
array2 = np.random.rand(100)
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]
print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation Coefficient:", correlation_coefficient)

Array 1: [8.07628365e-01 1.52359452e-01 9.66600315e-01 1.52154866e-01
 2.13137644e-01 7.44436425e-01 1.39235619e-01 2.07290193e-01
 2.25670673e-01 4.54755231e-02 4.81415179e-01 1.61559898e-01
 9.23232977e-01 9.96472597e-01 5.92906180e-01 9.69146204e-01
 8.29580314e-01 2.67974167e-01 6.82842786e-01 4.07774560e-01
 1.53494639e-01 4.49310845e-01 1.90293553e-01 5.70352910e-02
 9.77936788e-01 9.01627477e-01 9.11627225e-01 1.37917958e-01
 1.15458419e-01 7.91208136e-02 5.68589952e-01 4.01275142e-01
 7.09181120e-01 8.67730029e-02 2.01965497e-02 9.27928442e-01
 9.99500976e-01 5.09704113e-01 2.77354857e-01 6.42630030e-01
 2.00324808e-01 6.91873838e-01 8.59102846e-01 4.95558168e-01
 7.10274119e-04 4.10506518e-01 3.26163256e-01 2.21264695e-01
 6.71681116e-02 4.21416332e-01 2.68094758e-01 4.06813473e-01
 8.19542138e-01 9.82619134e-01 6.64081107e-01 6.49712890e-01
 8.53962876e-01 1.75521978e-01 3.16791487e-01 5.06924737e-02
 7.37537611e-01 3.72589410e-01 5.04171617e-01 1.80611065e-01
 1.68977785e-01

In [ ]:
#Q64. . Create two matrices and perform matrix multiplication using NumPy's `dot` function
#ans-
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result = np.dot(matrix1, matrix2)
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
#ans-
random_numbers = np.random.randint(10, 1001, size=50)
percentiles = np.percentile(random_numbers, [10, 50, 90])
first_quartile = np.percentile(random_numbers, 25)
third_quartile = np.percentile(random_numbers, 75)
print("Array of random numbers:", random_numbers)
print("10th Percentile:", percentiles[0])
print("50th Percentile (Median):", percentiles[1])
print("90th Percentile:", percentiles[2])
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)

Array of random numbers: [579 382 532 505 944 804 225 729 245 166 165 989 761 303 368 189 822 834
 298 254 322 738  34 182 336 316 689 506 413  63 338 763 715 504 319 912
 775 560  83 439 533  55 111 538 698 818 777 414 287 632]
10th Percentile: 159.60000000000002
50th Percentile (Median): 471.5
90th Percentile: 818.4
First Quartile (25th Percentile): 289.75
Third Quartile (75th Percentile): 725.5


In [ ]:
#Q66. Create a NumPy array of integers and find the index of a specific element.
#ans-
array = np.array([10, 20, 30, 40, 50])
element_to_find = 30 # Example
index = np.where(array == element_to_find)[0]
print("Array:", array)
print("Index of", element_to_find, ":", index)

Array: [10 20 30 40 50]
Index of 30 : [2]


In [ ]:
#Q67. Generate a random NumPy array and sort it in ascending order
#ans-
random_array = np.random.randint(1, 100, size=10)
np.sort(random_array)

array([ 9, 14, 32, 37, 39, 57, 69, 80, 92, 98])

In [ ]:
#Q68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
#ans-
filtered_arr = arr[arr > 20]
print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_arr)

Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [ ]:
#Q69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
#Ans
filtered_arr = arr[arr % 3 == 0]
filtered_arr

array([12, 15])

In [ ]:
#Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Original Array:", arr)
print("Filtered Array (elements between 20 and 40):", filtered_arr)

Original Array: [10 20 30 40 50]
Filtered Array (elements between 20 and 40): [20 30 40]


In [ ]:
import numpy as np
#Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
#Ans-
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)

=


In [ ]:
#Q72.  For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
#Ans-
arr.byteswap(inplace=True)
print(arr)

[16777216 33554432 50331648]


In [ ]:
#Q73.  For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
#Ans-
arr_swapped = arr.newbyteorder()
print(arr_swapped)

[16777216 33554432 50331648]


In [ ]:
#Q74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
#Ans-
if arr.dtype.byteorder == '=':
    # System has native byte order, no need to swap
    arr_swapped = arr
else:
    # System has different byte order, swap
    arr_swapped = arr.newbyteorder()
print(arr_swapped)

[1 2 3]


In [ ]:
#Q75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
#Ans-
if arr.dtype.byteorder != '=':
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")

Byte swapping is not necessary for the current system.


In [ ]:
#Q76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
#Ans-
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100# Modify an element in copy_arr
# Check if modifying copy_arr affects arr1
print("Original array (arr1):", arr1)
print("Copied array (copy_arr):", copy_arr)

Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Copied array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [ ]:
#Q77.  Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix
#Ans-
matrix = np.random.randint(1, 100, size=(3, 3))
print("Original matrix:")

view_slice = matrix[:2, :2]  # Taking the top-left 2x2 submatrix
view_slice[0, 0] = 999
print("\nModified view_slice:")
print(view_slice)
print("\nOriginal matrix after modifying view_slice:")
print(matrix)

Original matrix:
[[ 7 43 25]
 [26  6 65]
 [66 92 31]]

Modified view_slice:
[[999  43]
 [ 26   6]]

Original matrix after modifying view_slice:
[[999  43  25]
 [ 26   6  65]
 [ 66  92  31]]


In [ ]:
#Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
#Ans-
# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)
# Print the original array_a
print("Original array_a:")
print(array_a)
# Extract a slice view_b from array_a
view_b = array_a[1:3, 1:3]  # Extracting a 2x2 slice starting from the second row and second column
# Broadcast the addition of 5 to view_b
view_b += 5
# Print the modified view_b
print("\nModified view_b:")
print(view_b)
# Print the original array_a to observe if it's changed
print("\nOriginal array_a after modifying view_b:")
print(array_a)

Original array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Modified view_b:
[[10 11]
 [13 14]]

Original array_a after modifying view_b:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


In [ ]:
#Q79.  Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
#ans-
# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)
# Print the original orig_array
print("Original orig_array:")
print(orig_array)
# Create a reshaped view reshaped_view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)
# Modify an element in reshaped_view
reshaped_view[0, 0] = 100
# Print the modified reshaped_view
print("\nModified reshaped_view:")
print(reshaped_view)
# Print the original orig_array to observe if it reflects changes
print("\nOriginal orig_array after modifying reshaped_view:")
print(orig_array)

Original orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Modified reshaped_view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original orig_array after modifying reshaped_view:
[[100   2   3   4]
 [  5   6   7   8]]


In [ ]:
#Q80.  Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
#Ans=
# Create a NumPy array of shape (3, 4) with random integers
data = np.random.randint(0, 10, size=(3, 4))
print("Original data:")
print(data)
# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()
print("\nCopy of elements greater than 5:")
print(data_copy)
# Modify an element in data_copy
data_copy[0, 0] = 10
# Verify if it affects the original data
print("\nOriginal data after modifying data_copy:")
print(data)
print("\nCopy of elements greater than 5 after modification:")
print(data_copy)

Original data:
[[5 5 8 6]
 [9 4 0 1]
 [0 5 7 4]]

Copy of elements greater than 5:
[8 6 9 7]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
#Q81.  Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them
#ans-
# Create two matrices A and B of identical shape containing integers
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])
# Perform addition and subtraction operations between them
addition_result = A + B
subtraction_result = A - B
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition Result (A + B):")
print(addition_result)
print("\nSubtraction Result (A - B):")
print(subtraction_result)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition Result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction Result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
#Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
#Ans-
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])
# Perform matrix multiplication
multiplication_result = np.dot(C, D)
print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)
print("\nMatrix Multiplication Result (C x D):")
print(multiplication_result)

Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix Multiplication Result (C x D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [ ]:
#Q83. Create a matrix `E` and find its transpose.
#Abs-
# Create a matrix E
E = np.array([[1, 2, 3],
              [4, 5, 6]])
E_transpose = np.transpose(E)
print("Matrix E:")
print(E)
print("\nTranspose of Matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of Matrix E:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Q84. Generate a square matrix `F` and compute its determinant.
#Ans-
# Generate a square matrix F
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)
print("Matrix F:")
print(F)
print("\nDeterminant of Matrix F:", determinant_F)

Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix F: 0.0


In [ ]:
#Q85. Create a square matrix `G` and find its inverse.
#Ans-
# Create a square matrix G
G = np.array([[1, 2],
              [3, 4]])
inverse_G = np.linalg.inv(G) # Find the inverse of matrix G
print("Matrix G:")
print(G)
print("\nInverse of Matrix G:")
print(inverse_G)

Matrix G:
[[1 2]
 [3 4]]

Inverse of Matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
